name: afl_model_library
description: "A shared package containing common data models with JSON serialization support"
version: 0.0.1
publish_to: "https://github.com/nzetala/AFL_shared_model_library"
repository: "https://github.com/nzetala/AFL_shared_model_library"
homepage: 'https://github.com/nzetala/AFL_shared_model_library'

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.0.4
  build_runner_core: ^7.2.9
  json_serializable: ^6.8.0

# The following section is specific to Flutter packages.
#flutter:
